name: cross-platform-builds
on:
  push:
    branches:
      - main
env:
  APP_NAME: magasin

jobs:
  ios:
    runs-on: macos-15
    
    steps:
    - uses: actions/checkout@v5
    - run: make init
    - run: make ios-pod-update

    - run: fvm flutter build ios --release --no-codesign

    - name: Package .app into .ipa
      run: |
        mkdir -p Payload
        cp -R build/ios/iphoneos/Runner.app Payload/
        zip -r Runner.ipa Payload
        rm -rf Payload    
    
    - name: Upload iOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.APP_NAME }}-ios.ipa
        path: Runner.ipa

  macos:
    runs-on: macos-15
    
    steps:
    - uses: actions/checkout@v5
    - run: make init
    - run: make macos-pod-update

    - run: fvm flutter config --enable-macos-desktop
    - run: fvm flutter build macos --release
   
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
          name: ${{ env.APP_NAME }}-macos.app
          path: build/macos/Build/Products/Release/${{ env.APP_NAME }}.app

  android:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - run: make init

      - run: fvm flutter build apk --release --split-per-abi

      - name: Upload arm64-v8a APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-arm64-v8a.apk
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

      - name: Upload armeabi-v7a APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-armeabi-v7a.apk
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

      - name: Upload x86_64 APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-x86_64.apk
          path: build/app/outputs/flutter-apk/app-x86_64-release.apk

  linux-x64:
    runs-on: ubuntu-24.04
    
    steps:
    - uses: actions/checkout@v5
    - run: make init
    - run: sudo apt-get install build-essential libgtk-3-dev

    - run: fvm flutter config --enable-linux-desktop
    - run: fvm flutter build linux --release --target-platform=linux-x64

    - name: Upload Linux x64 artifact
      uses: actions/upload-artifact@v4
      with:
          name: ${{ env.APP_NAME }}-linux-x64
          path: build/linux/x64/release/bundle/${{ env.APP_NAME }}

  linux-arm64:
    runs-on: ubuntu-24.04-arm
    
    steps:
    - uses: actions/checkout@v5
    - run: make init
    - run: sudo apt-get install build-essential libgtk-3-dev

    - run: fvm flutter config --enable-linux-desktop
    - run: fvm flutter build linux --release --target-platform=linux-arm64

    - name: Upload Linux arm64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.APP_NAME }}-linux-arm64
        path: build/linux/arm64/release/bundle/${{ env.APP_NAME }}

  windows:
    runs-on: windows-2025
    
    steps:
    - uses: actions/checkout@v5

    - run: choco install fvm
    - run: fvm install
    - run: fvm flutter pub get
    - run: fvm dart run build_runner build --delete-conflicting-outputs
    
    - run: fvm flutter config --enable-windows-desktop
    - run: fvm flutter build windows --release

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
          name: ${{ env.APP_NAME }}-windows-x64
          path: build\windows\x64\runner\Release
